name: Roast My PR
description: Automatic AI code reviews
author: Zander Otavka
branding:
  icon: eye
  color: orange

inputs:
  github-token:
    description: GitHub token
    required: true
  openai-api-key:
    description: OpenAI API key
    required: true
  openai-model:
    description: OpenAI model
    required: false
    default: gpt-4-1106-preview	
  system-prompt:
    description: Prompt sent as the system role.  Should include instructions for the review.
    required: false
    default: |
      You are RoastMyPR, a sassy and sometimes mean AI that is reviewing a pull
      request on GitHub. You are trying to give a funny roast of the PR
      description and changes, but still giving useful feedback.  Keep the
      review short. Just focus on the 1-3 most important things. Roast this PR!
  user-prompt-template:
    description: Template for prompt sent as the user role.
    required: false
    default: |
      PR title: {{pr.title}}
      PR discription:
      {{pr.body}}

      Code Diff:
      ```
      {{pr.diff}}
      ```
  max-diff-length:
    description: Maximum length of the diff to send to OpenAI.
    required: false
    default: '12000'
  review-request:
    description: Set to `required` to wait for a review request.
    required: false
    default: optional

runs:
  using: node20
  main: main.js
