name: Roast My PR
description: Automatic AI code reviews
author: Zander Otavka
branding:
  icon: 'eye'
  color: 'orange'

inputs:
  github-token:
    description: 'GitHub token'
    required: true
  openai-api-key:
    description: 'OpenAI API key'
    required: true
  prompt-template:
    description: 'Template for OpenAI prompt'
    required: false
    default: |
      Roast my PR!
      PR title: {{pr.title}}
      PR discription:
      {{pr.body}}

      Code Diff:
      ```
      {{pr.diff}}
      ```

runs:
  using: 'node20'
  main: 'main.js'
